; PlatformIO Project Configuration File
;
; ESP32-S3 Barcode Scanner
; Board: ESP32-S3-DevKitC-1 (N16R8)
; Framework: Arduino
;
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions.csv
board_upload.flash_size = 16MB
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi

lib_deps = 
    lvgl/lvgl@^8.4.0
    lovyan03/LovyanGFX@^1.1.12
    bblanchon/ArduinoJson@^7.0.4
    ricmoo/QRCode@^0.0.1
    knolleary/PubSubClient@^2.8
    https://github.com/espressif/esp32-camera.git

build_flags = 
    -D BOARD_HAS_PSRAM
    -D LV_CONF_INCLUDE_SIMPLE
    -D CAMERA_MODEL_CUSTOM
    -I.
    -Isrc/config

monitor_filters = esp32_exception_decoder
